version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: db-dev
      POSTGRES_PASSWORD: 12345678
    networks:
      - default
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://root:12345678@db:5432/db-dev
      - PORT=3000
      - CONTACT_ADDRESS=0x280474b946C3C7931f6CBEc74a4a43bC3B5C6996
    depends_on:
      - db
    networks:
      - default
networks:
  default:
